name: J. Eatley / Photographer
favicon: null
layout_spectrum: 0.9901530821807683
typography_spectrum: 0.020404472714290023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06357890018261969
  lightness: 0.5858750166371465
  saturation: 0.4595441159326583
  rhythmicContrast: 0.22248927527107298
purpose: []
